export const COUNTRIES = [
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "Canada", code: "CA" },
  { name: "Ireland", code: "IE" },
  { name: "Germany", code: "DE" },
  { name: "France", code: "FR" },
  { name: "Italy", code: "IT" },
  { name: "Switzerland", code: "CH" },
  { name: "Austria", code: "AT" },
  { name: "Spain", code: "ES" },
  { name: "Netherlands", code: "NL" },
  { name: "Belgium", code: "BE" },
  { name: "Denmark", code: "DK" },
  { name: "Sweden", code: "SE" },
  { name: "Norway", code: "NO" },
  { name: "Portugal", code: "PT" },
  { name: "Finland", code: "FI" },
  { name: "Belarus", code: "BY" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Bulgaria", code: "BG" },
  { name: "Croatia", code: "HR" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Estonia", code: "EE" },
  { name: "Georgia", code: "GE" },
  { name: "Greece", code: "GR" },
  { name: "Hungary", code: "HU" },
  { name: "Latvia", code: "LV" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Poland", code: "PL" },
  { name: "Romania", code: "RO" },
  { name: "Russia", code: "RU" },
  { name: "Senegal", code: "SN" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Ukraine", code: "UA" },
  { name: "American Samoa", code: "AS" },
  { name: "Serbia", code: "RS" },
  { name: "Montenegro", code: "ME" },
];
