export const COUNTRIES = [
  { name: "United Kingdom", code: "GB" },
  { name: "Jersey", code: "JE" },
  { name: "Guernsey", code: "GG" },
  { name: "Isle of Man", code: "IM" },
  { name: "United States", code: "US" },
  { name: "Canada", code: "CA" },
  { name: "Ireland", code: "IE" },
  { name: "Germany", code: "DE" },
  { name: "Japan", code: "JP" },
  { name: "France", code: "FR" },
  { name: "Australia", code: "AU" },
  { name: "Italy", code: "IT" },
  { name: "Switzerland", code: "CH" },
  { name: "Austria", code: "AT" },
  { name: "Spain", code: "ES" },
  { name: "Netherlands", code: "NL" },
  { name: "Belgium", code: "BE" },
  { name: "Denmark", code: "DK" },
  { name: "Sweden", code: "SE" },
  { name: "Norway", code: "NO" },
  { name: "Brazil", code: "BR" },
  { name: "Portugal", code: "PT" },
  { name: "Finland", code: "FI" },
  { name: "Åland Islands", code: "AX" },
  { name: "South Korea", code: "KR" },
  { name: "China", code: "CN" },
  { name: "Taiwan", code: "TW" },
  { name: "Singapore", code: "SG" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Bermuda", code: "BM" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Cambodia", code: "KH" },
  { name: "Cape Verde", code: "CV" },
  { name: "Chile", code: "CL" },
  { name: "Costa Rica", code: "CR" },
  { name: "Croatia", code: "HR" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "Estonia", code: "EE" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Georgia", code: "GE" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Guatemala", code: "GT" },
  { name: "Haiti", code: "HT" },
  { name: "Honduras", code: "HN" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Israel", code: "IL" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kuwait", code: "KW" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Laos", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "North Macedonia", code: "MK" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Malta", code: "MT" },
  { name: "Mauritius", code: "MU" },
  { name: "Mexico", code: "MX" },
  { name: "Moldova", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Morocco", code: "MA" },
  { name: "Nepal", code: "NP" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Nigeria", code: "NG" },
  { name: "Oman", code: "OM" },
  { name: "Panama", code: "PA" },
  { name: "Pakistan", code: "PK" },
  { name: "Paraguay", code: "PY" },
  { name: "Philippines", code: "PH" },
  { name: "Poland", code: "PL" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Romania", code: "RO" },
  { name: "Russia", code: "RU" },
  { name: "San Marino", code: "SM" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "South Africa", code: "ZA" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Thailand", code: "TH" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Ukraine", code: "UA" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vatican City", code: "VA" },
  { name: "Venezuela", code: "VE" },
  { name: "Zambia", code: "ZM" },
  { name: "American Samoa", code: "AS" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Cook Islands", code: "CK" },
  { name: "Serbia", code: "RS" },
  { name: "Montenegro", code: "ME" },
  { name: "Serbia and Montenegro", code: "CS" }, // устаревшее
  { name: "Yugoslavia", code: "YU" }, // устаревшее
  { name: "Christmas Island", code: "CX" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands", code: "FK" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Micronesia", code: "FM" },
  { name: "French Guiana", code: "GF" },
  { name: "Guinea", code: "GN" },
  { name: "Guadeloupe", code: "GP" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "Guam", code: "GU" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Heard Island and McDonald Islands", code: "HM" },
  { name: "Iraq", code: "IQ" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Liberia", code: "LR" },
  { name: "Lesotho", code: "LS" },
  { name: "Madagascar", code: "MG" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Mongolia", code: "MN" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Martinique", code: "MQ" },
  { name: "New Caledonia", code: "NC" },
  { name: "Niger", code: "NE" },
  { name: "U.S. Virgin Islands", code: "VI" },
  { name: "Vietnam", code: "VN" },
  { name: "French Polynesia", code: "PF" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Pitcairn Islands", code: "PN" },
  { name: "Palau", code: "PW" },
  { name: "Réunion", code: "RE" },
  { name: "Saint Helena", code: "SH" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Somalia", code: "SO" },
  { name: "Eswatini", code: "SZ" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Kosovo", code: "XK" },
  { name: "Mayotte", code: "YT" },
  { name: "Peru", code: "PE" },
  { name: "Gibraltar", code: "GI" },
  { name: "Bhutan", code: "BT" },
  { name: "Albania", code: "AL" },
  { name: "Cuba", code: "CU" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Anguilla", code: "AI" },
  { name: "Afghanistan", code: "AF" },
  { name: "Sudan", code: "SD" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Tristan da Cunha", code: "TA" },
  { name: "Namibia", code: "NA" },
  { name: "Western Sahara", code: "EH" },
  { name: "Saint Barthélemy", code: "BL" },
  { name: "Tanzania", code: "TZ" },
  { name: "Ascension Island", code: "AC" },
  { name: "British Virgin Islands", code: "VG" },
  { name: "Mozambique", code: "MZ" },
  { name: "Saint Martin", code: "MF" },
  { name: "Myanmar", code: "MM" },
  { name: "El Salvador", code: "SV" },
  { name: "Iran", code: "IR" },
  { name: "International", code: "INTL" },
  { name: "Colombia", code: "CO" },
];
